### ISSUE TITLE
Header BG UI Tweak

### ISSUE THREAD

**Issue by merittthomas** [jstnjns/cloudlist#12]
Change:

```css
#header .current-header .background { opacity: 0.25; }
```
To:

```css
#header .current-header .background { opacity: 0.65; }
```
